# -*- coding: utf-8 -*-
"""09012026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bBkgCQoRG1qERDYD48zKzNJJ5BupJ8XR

# Phan 1
"""

!pip install yfinance pandas numpy sqlalchemy

import yfinance as yf
import pandas as pd
from datetime import datetime
import time

tickers_list = [
    "VIC.VN",  # Vingroup
    "VND.VN",  # VNDirect
    "HPG.VN",  # Hoa Phat
    "SSI.VN",  # SSI
    "VCB.VN",  # Vietcombank
    "BID.VN",  # BIDV
    "GAS.VN",  # PV Gas
    "MSN.VN",  # Masan
    "MWG.VN",  # Mobile World
    "TCB.VN"   # Techcombank
]

START_DATE = "2020-01-01"
END_DATE = datetime.today().strftime("%Y-%m-%d")

all_data = []

for ticker_symbol in tickers_list:
    print(f"\n📥 Đang tải dữ liệu cho {ticker_symbol} ...")

    try:
        ticker = yf.Ticker(ticker_symbol)
        df = ticker.history(
            start=START_DATE,
            end=END_DATE,
            interval="1d",
            auto_adjust=True
        )

        if df.empty:
            print(f"⚠️ Không có dữ liệu cho {ticker_symbol}")
            continue

        df = df.reset_index()
        df["ticker"] = ticker_symbol

        # Chuẩn hóa tên cột
        df = df.rename(columns={
            "Date": "date",
            "Open": "open",
            "High": "high",
            "Low": "low",
            "Close": "close",
            "Volume": "volume"
        })

        df = df[["ticker", "date", "open", "high", "low", "close", "volume"]]

        all_data.append(df)

        print(f"✅ {ticker_symbol}: {len(df)} dòng")

        time.sleep(1)  # ⭐ RẤT QUAN TRỌNG với Yahoo VN

    except Exception as e:
        print(f"❌ Lỗi với {ticker_symbol}: {e}")

price_df = pd.concat(all_data, ignore_index=True)

price_df["date"] = pd.to_datetime(price_df["date"]).dt.date

price_df.head()

price_df.tail()

price_df.info()

"""Phan 2"""

price_df = price_df.sort_values(
    by=["ticker", "date"]
).reset_index(drop=True)

price_df.head()

price_df["future_close_5d"] = (
    price_df
    .groupby("ticker")["close"]
    .shift(-5)
)

price_df["future_return_5d"] = (
    price_df["future_close_5d"] - price_df["close"]
) / price_df["close"]

price_df[["ticker", "date", "close", "future_close_5d", "future_return_5d"]].head(10)

def label_signal(ret):
    if ret > 0.07:
        return "BUY"
    elif ret < -0.05:
        return "SELL"
    else:
        return "HOLD"

price_df["label"] = price_df["future_return_5d"].apply(label_signal)

price_df[["ticker", "date", "future_return_5d", "label"]].head(10)

price_df["label"].value_counts(normalize=True)

price_df_labeled = price_df.dropna(subset=["future_return_5d"]).copy()

price_df_labeled.info()

price_df_labeled.to_csv("price_daily_vn_labeled.csv", index=False)

"""# Phan 3

"""

import numpy as np

def compute_rsi(series, window=14):
    delta = series.diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)

    avg_gain = gain.rolling(window).mean()
    avg_loss = loss.rolling(window).mean()

    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))
    return rsi

price_df_labeled["rsi_14"] = (
    price_df_labeled
    .groupby("ticker")["close"]
    .transform(lambda x: compute_rsi(x, 14))
)

price_df_labeled[["ticker", "date", "close", "rsi_14"]].head(20)

price_df_labeled["return_1d"] = (
    price_df_labeled
    .groupby("ticker")["close"]
    .pct_change()
)

price_df_labeled["return_5d"] = (
    price_df_labeled
    .groupby("ticker")["close"]
    .pct_change(5)
)

price_df_labeled["volatility_10d"] = (
    price_df_labeled
    .groupby("ticker")["return_1d"]
    .rolling(10)
    .std()
    .reset_index(level=0, drop=True)
)

price_df_labeled["ma_5"] = (
    price_df_labeled
    .groupby("ticker")["close"]
    .rolling(5)
    .mean()
    .reset_index(level=0, drop=True)
)

price_df_labeled["ma_20"] = (
    price_df_labeled
    .groupby("ticker")["close"]
    .rolling(20)
    .mean()
    .reset_index(level=0, drop=True)
)

price_df_labeled["ma_50"] = (
    price_df_labeled
    .groupby("ticker")["close"]
    .rolling(50)
    .mean()
    .reset_index(level=0, drop=True)
)

price_df_labeled["ma_200"] = (
    price_df_labeled
    .groupby("ticker")["close"]
    .rolling(200)
    .mean()
    .reset_index(level=0, drop=True)
)

price_df_labeled["ma_diff"] = (
    price_df_labeled["ma_5"] - price_df_labeled["ma_20"]
) / price_df_labeled["close"]

def slope_last_window(y):
    x = np.arange(len(y))
    return np.polyfit(x, y, 1)[0]

price_df_labeled["trend_slope_20d"] = (
    price_df_labeled
    .groupby("ticker")["close"]
    .rolling(window=20)
    .apply(slope_last_window, raw=True)
    .reset_index(level=0, drop=True)
)

price_df_labeled[["ticker", "date", "close", "trend_slope_20d"]].head(25)

"""# Phan 4"""

import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.cluster import KMeans

df_wyckoff = price_df_labeled.copy()
df_wyckoff = df_wyckoff.sort_values(["ticker", "date"]).reset_index(drop=True)

# Biên độ dao động
df_wyckoff["spread"] = (df_wyckoff["high"] - df_wyckoff["low"]) / df_wyckoff["close"]

# Vị trí đóng cửa trong nến
df_wyckoff["close_location"] = (
    (df_wyckoff["close"] - df_wyckoff["low"]) /
    (df_wyckoff["high"] - df_wyckoff["low"] + 1e-6)
)

# Volume ratio
df_wyckoff["volume_ma_20"] = (
    df_wyckoff.groupby("ticker")["volume"]
    .transform(lambda x: x.rolling(20).mean())
)

df_wyckoff["volume_ratio"] = (
    df_wyckoff["volume"] / (df_wyckoff["volume_ma_20"] + 1e-6)
)

df_wyckoff["price_change"] = (
    df_wyckoff.groupby("ticker")["close"].diff()
)

df_wyckoff["effort_up"] = (
    np.maximum(df_wyckoff["price_change"], 0)
    / (df_wyckoff["volume_ratio"] + 1e-6)
)

df_wyckoff["effort_down"] = (
    np.maximum(-df_wyckoff["price_change"], 0)
    / (df_wyckoff["volume_ratio"] + 1e-6)
)

# MA200
df_wyckoff["ma_200"] = (
    df_wyckoff.groupby("ticker")["close"]
    .transform(lambda x: x.rolling(200).mean())
)

# Khoảng cách tới MA200
df_wyckoff["dist_ma200"] = (
    (df_wyckoff["close"] - df_wyckoff["ma_200"]) /
    (df_wyckoff["ma_200"] + 1e-6)
)

df_wyckoff["range_low_60"] = (
    df_wyckoff.groupby("ticker")["low"]
    .transform(lambda x: x.rolling(60).min())
)

df_wyckoff["range_high_60"] = (
    df_wyckoff.groupby("ticker")["high"]
    .transform(lambda x: x.rolling(60).max())
)

df_wyckoff["range_position"] = (
    (df_wyckoff["close"] - df_wyckoff["range_low_60"]) /
    (df_wyckoff["range_high_60"] - df_wyckoff["range_low_60"] + 1e-6)
)

wyckoff_features = [
    "spread",
    "close_location",
    "volume_ratio",
    "effort_up",
    "effort_down",
    "dist_ma200",
    "trend_slope_20d",
    "range_position"
]

df_w = df_wyckoff.dropna(subset=wyckoff_features).copy()

scaler = StandardScaler()
X = scaler.fit_transform(df_w[wyckoff_features])

kmeans = KMeans(
    n_clusters=4,
    random_state=42,
    n_init=20
)

df_w["cluster_id"] = kmeans.fit_predict(X)

profile = df_w.groupby("cluster_id")[wyckoff_features].mean()

mapping = {}

# ACCUMULATION:
# Gần MA200 + range thấp + trend yếu
acc = (
    profile["dist_ma200"].abs()
    + profile["range_position"]
    + profile["trend_slope_20d"].abs()
).idxmin()
mapping[acc] = 0  # ACCUMULATION

# MARKUP:
# Trend tăng mạnh nhất
markup = profile["trend_slope_20d"].idxmax()
mapping[markup] = 1  # MARKUP

# MARKDOWN:
# Effort_down lớn + trend yếu
markdown = (
    profile["effort_down"]
    - profile["trend_slope_20d"]
).idxmax()
mapping[markdown] = 3  # MARKDOWN

# DISTRIBUTION:
for c in profile.index:
    if c not in mapping:
        mapping[c] = 2  # DISTRIBUTION

df_w["wyckoff_kmeans"] = df_w["cluster_id"].map(mapping)

cluster_profile = (
    df_w.groupby("cluster_id")[wyckoff_features].mean()
)

cluster_profile_scaled = cluster_profile.copy()
for col in cluster_profile.columns:
    min_v = cluster_profile[col].min()
    max_v = cluster_profile[col].max()
    cluster_profile_scaled[col] = (
        (cluster_profile[col] - min_v) / (max_v - min_v + 1e-6)
    )

def plot_wyckoff_radar(data, features, mapping):
    import numpy as np
    import matplotlib.pyplot as plt

    angles = np.linspace(0, 2 * np.pi, len(features), endpoint=False)
    angles = np.append(angles, angles[0])

    fig, axes = plt.subplots(
        1, len(data),
        figsize=(5 * len(data), 5),
        subplot_kw=dict(polar=True)
    )

    for ax, cid in zip(axes, data.index):
        values = data.loc[cid].values
        values = np.append(values, values[0])

        ax.plot(angles, values, linewidth=2)
        ax.fill(angles, values, alpha=0.25)

        ax.set_thetagrids(
            angles[:-1] * 180 / np.pi,
            features,
            fontsize=9
        )

        market = {
            0: "ACCUMULATION",
            1: "MARKUP",
            2: "DISTRIBUTION",
            3: "MARKDOWN"
        }[mapping[cid]]

        ax.set_title(
            f"Cluster {cid}\n{market}",
            fontsize=12,
            pad=18
        )
        ax.set_ylim(0, 1)

    plt.suptitle(
        "Radar Chart – Wyckoff Clusters (Final)",
        fontsize=16,
        y=1.08
    )
    plt.tight_layout()
    plt.show()

plot_wyckoff_radar(
    cluster_profile_scaled,
    wyckoff_features,
    mapping
)

if "wyckoff_kmeans" in price_df_labeled.columns:
    price_df_labeled = price_df_labeled.drop(columns=["wyckoff_kmeans"])

price_df_labeled = price_df_labeled.merge(
    df_w[["ticker", "date", "wyckoff_kmeans"]],
    on=["ticker", "date"],
    how="left"
)

"""# Phan 7"""

price_df_labeled.columns.tolist()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
price_df_labeled["label_encoded"] = le.fit_transform(
    price_df_labeled["label"]
)

final_features = [
    # Momentum
    "rsi_14",
    "return_1d",
    "return_5d",

    # Volatility
    "volatility_10d",

    # Trend structure
    "ma_diff",
    "trend_slope_20d",

    # Market context
    "wyckoff_kmeans",

]

df_buy  = price_df_labeled[price_df_labeled["label"] == "BUY"]
df_sell = price_df_labeled[price_df_labeled["label"] == "SELL"]
df_hold = price_df_labeled[price_df_labeled["label"] == "HOLD"]

df_hold_sampled = df_hold.sample(
    frac=0.3,
    random_state=42
)

final_df = pd.concat(
    [df_buy, df_sell, df_hold_sampled],
    axis=0
).sample(frac=1, random_state=42)

label_map = {
    "SELL": 0,
    "HOLD": 1,
    "BUY": 2
}

final_df["label_encoded"] = final_df["label"].map(label_map)

X = final_df[final_features]
y = final_df["label_encoded"]

split_date = pd.to_datetime("2024-01-01")

final_df["date"] = pd.to_datetime(final_df["date"])

train_idx = final_df["date"] < split_date
test_idx  = final_df["date"] >= split_date

X_train, X_test = X[train_idx], X[test_idx]
y_train, y_test = y[train_idx], y[test_idx]

y.value_counts(normalize=True)

from xgboost import XGBClassifier
xgb_final = XGBClassifier(
    objective="multi:softmax",
    num_class=3,
    n_estimators=500,
    max_depth=4,
    learning_rate=0.03,
    subsample=0.9,
    colsample_bytree=0.9,
    min_child_weight=5,
    eval_metric="mlogloss",
    random_state=42
)
xgb_final.fit(
    X_train,
    y_train,
)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = xgb_final.predict(X_test)

print("Final XGBoost Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred, target_names=["SELL", "HOLD", "BUY"]))

from sklearn.metrics import balanced_accuracy_score

print("Balanced Accuracy:", balanced_accuracy_score(y_test, y_pred))

import joblib

joblib.dump(xgb_final, "xgboost_final_stock_model.pkl")

from google.colab import files
files.download("xgboost_final_stock_model.pkl")

final_df.to_csv("stock_ml_dataset.csv", index=False)

files.download("stock_ml_dataset.csv")

"""python -m streamlit run Hệ_thống.py

*   Mục danh sách
*   Mục danh sách



uvicorn backend.main:app --reload

.\venv\Scripts\Activate.ps1
"""